version: '3.8'

services:
    web:
        image: nginx:1.25.3-alpine
        container_name: web
        working_dir: /app
        volumes:
            - ./docker/nginx/config.conf:/etc/nginx/conf.d/default.conf
            - ./application:/app
        networks:
            - app-net
        ports:
            - 80:80
        depends_on:
            - php

    php:
        container_name: php
        working_dir: /app
        volumes:
            - ./application:/app
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        networks:
            - app-net

networks:
    app-net:
        driver: bridge